### ISSUE TITLE
这块实时计算的逻辑是否可以更加高效？

### ISSUE THREAD

**Issue by zs121233** [echoface/be_indexer#14]
https://github.com/echoface/be_indexer/blob/a569297f79b02505a596e1a7fa9aa9de9ba72571/entries_holder.go#L75

1.多值查询（A  or  B）中，对同一个属性下面的多个key有多个entries。这些entries需要取并集，并重新排序。
如果entries已经有序，在合并时通过n 有序列表合并的方式会更加高效。
2.此外多值查询可能不止是A  or  B，可能是 A and B。是否需要提供一个多个entries取并集的场景

**Comment by echoface** [comment]
不好意思, 最近在忙其他事情, 没有关注到这个问题. 
A1.
按照论文的描述:  对于一个DNF 中一个Conjunction 的描述:  {tag  in/not in [v1, v2, v3]}  指tag 需要满足 v1,v2,v3 中任意一个(这里暂时假设成in逻辑). 那么对于一个文档: doc 它的tag属性是: v2, v11; 对于布尔表达式`{tag  in/not in [v1, v2, v3]}` 显然是满足的.  目前多值查询上, 是构造了多个访问posting list(entries) 的cursor.  并在skip[to]过程中按照排序的形式进行的,所以并不需要在retrieve 时做entries sort的操作, 具体可以参考FieldCursor部分
A2.
对于你这里说的查询A or B . 我理解这里描述的A,B 是指维度field.  因为这里是对布尔逻辑的索引. OR/ AND 的逻辑体现在布尔文档构造Index的过程中已经处理了, 对于查询,只需要提供Assign的属性即可, 并没有and/or的逻辑概念. 举个例子
doc 1: [{age  in [18-30]}, {tag in [X粉丝团]}, {gender not in [男]}  对于这样一个DNF, 描述的布尔逻辑: 年龄在18-20岁 **且** tag 是 X粉丝团 标签 **且** 非男性      当一个流量或者一个用户的上下文信息: age: 25,  tag: [“汽车爱好者”, ‘X粉丝’]  性别: 未知
从布尔逻辑匹配来看: 这个用户/请求 对于 布尔文档doc1  的结果是: true (即满足doc1要求的)

**Comment by zs121233** [comment]
好的感谢回答，我再研读一下代码。
公司内部的布尔检索也是参考这篇文章实现的，所以想看看有没有好的优化/实践 方案。

**Comment by zs121233** [comment]
另外就是，增量索引是如何做更新的呢？

**Comment by zs121233** [comment]
另外好像没看到delet doc 或者  update操作。增量索引应该怎么做呀  0-0

**Comment by echoface** [comment]
> 如果conjid与 docid相关的话，如果两个doc的conj完全相同，conjid还是有可能不同吗？

会不同， 可以看下conjunction id的生成逻辑， 可以简单的理解成conjctionid= docid << 48 |  index |  conj_size

**Comment by echoface** [comment]
> 另外好像没看到delet doc 或者 update操作。增量索引应该怎么做呀 0-0

这个逻辑更像是工程上使用这个库如何put/del/mod document，和其他大部分其他索引构建相似，一般都是使用定时构建。配合工程上的其他模块（eg: 分布式存储） 合理的将文档分布在不同机器上。 做分布式索引查询； 其他使用上的交流能微信交流吗: 添加微信：SuperHgO

**Comment by showntop** [comment]
> 

这里也有同样疑问，索引的更新涉及到全量和增量，put/del/mod document 会涉及到索引的修改，如果不实现的话，这里的意图是要每次全量构建索引吗？

**Comment by echoface** [comment]
> > 
> 
> 这里也有同样疑问，索引的更新涉及到全量和增量，put/del/mod document 会涉及到索引的修改，如果不实现的话，这里的意图是要每次全量构建索引吗？

如果将索引作为一个服务，当广告的定向被修改后。业务将其转化成布尔文档后发布到索引服务（假设成es）,索引服务按照其固定的策略重构索引数据，从生效时效和功能上评估并没有什么问题；其不能像关系型数据库索引一样实时更新与其逻辑关系有关，并不是简单多键值索引。在做好分片后，索引数据的构建速度应该并无什么明显问题，因为文档是逻辑完整的从一个版本换到另一个版本。从接触到的广告系统来看，定向只是最基础的部分，后面还有一些列的反馈控制和其他非布尔逻辑过滤,从而最终得到召回的广告

**Comment by echoface** [comment]
> 如果conjid与 docid相关的话，如果两个doc的conj完全相同，conjid还是有可能不同吗？

conjid是由docid 以及 是一个doc中第几个conjunction、conjunction的size编码得到的，所以conjunction逻辑表达完全一样。最终的conjid是不同的

**Comment by showntop** [comment]
> > > 
> > 
> > 
> > 这里也有同样疑问，索引的更新涉及到全量和增量，put/del/mod document 会涉及到索引的修改，如果不实现的话，这里的意图是要每次全量构建索引吗？
> 
> 如果将索引作为一个服务，当广告的定向被修改后。业务将其转化成布尔文档后发布到索引服务（假设成es）,索引服务按照其固定的策略重构索引数据，从生效时效和功能上评估并没有什么问题；其不能像关系型数据库索引一样实时更新与其逻辑关系有关，并不是简单多键值索引。在做好分片后，索引数据的构建速度应该并无什么明显问题，因为文档是逻辑完整的从一个版本换到另一个版本。从接触到的广告系统来看，定向只是最基础的部分，后面还有一些列的反馈控制和其他非布尔逻辑过滤,从而最终得到召回的广告

我理解索引的更新会是一个复杂的过程。如你所说，如果采用分片方式提升构建效率，那这里对索引分片的策略有什么好方法呢？比如5分钟产生了ad1，ad2 .... adn，那么如果简单哈希策略可能会涉及到多个极端n个分片的重建，这一般也是不能接受的吧

**Comment by echoface** [comment]
> > > > 
> > > 
> > > 
> > > 这里也有同样疑问，索引的更新涉及到全量和增量，put/del/mod document 会涉及到索引的修改，如果不实现的话，这里的意图是要每次全量构建索引吗？
> > 
> > 如果将索引作为一个服务，当广告的定向被修改后。业务将其转化成布尔文档后发布到索引服务（假设成es）,索引服务按照其固定的策略重构索引数据，从生效时效和功能上评估并没有什么问题；其不能像关系型数据库索引一样实时更新与其逻辑关系有关，并不是简单多键值索引。在做好分片后，索引数据的构建速度应该并无什么明显问题，因为文档是逻辑完整的从一个版本换到另一个版本。从接触到的广告系统来看，定向只是最基础的部分，后面还有一些列的反馈控制和其他非布尔逻辑过滤,从而最终得到召回的广告
> 
> 我理解索引的更新会是一个复杂的过程。如你所说，如果采用分片方式提升构建效率，那这里对索引分片的策略有什么好方法呢？比如5分钟产生了ad1，ad2 .... adn，那么如果简单哈希策略可能会涉及到多个极端n个分片的重建，这一般也是不能接受的吧

索引更新如果不做任何优化，就是划分的一个分片上所有文档的一次遍历, tokenize, entries sort 操作，存在CPU，内存的消耗，前两个步骤是可以优化的，做到只需要对有更新的文档进行。但是最后的entries合并与sort则没那么方便优化；第二个问题分片策略 一般采用分槽方式，文档不多时eg：几十万级，那就一个就够了，如果发现性能那个，CPU，内存存在瓶颈，那就对半分，再增长到千万级，那就再对照对半分的方式处理，当然也有其他管理调度的形式

**Comment by echoface** [comment]
目前top级公司一个业务在投放的计划（文档）也就千万级；再多可能在业务划分上就是两套系统甚至多个了eg：电商部分，品牌广告....等；索引基本上是为了极致的查询而优化的，目前对于常见的几种布尔文档索引的论文，目前没有了解到相关论文有在索引修改更新方面的结构优化，很早之前有见过基于树结构能够支持文档更新，但是那个是将一个文档作为逻辑整体的，算不上对“值”的索引，这方面@showntop 有可以提供参考的吗？
