### ISSUE TITLE
bug:retrieval msg 

### ISSUE THREAD

**Issue by bytezyp** [echoface/be_indexer#19]
json_doc case 召回的广告，不准确

**Comment by echoface** [comment]
能给个具体的case 吗?

**Comment by echoface** [comment]
> 
猜测到你说的问题了, 这个应该是最近的改动引入的问题. 因为BooleanValue/BooleanExpr定义的value 由原来的[]interface{} 转化成 interface了. 这个导致json doc 反序列化之后得到的Value parse时得到的值与修改前不一致导致; 我稍后fix一下这个example;  实际工程上应用不建议直接json反序列化doc(除非自己写定制化的parser); 而是定义业务具体结构转化成BeDocument

**Comment by echoface** [comment]
> 

fix @ https://github.com/echoface/be_indexer/pull/20
